import type { ItemFieldConfig } from "./ItemDialog";

export type ItemDefinition = {
  key: string;
  title: string;
  singularTitle: string;
  description: string;
  primaryField: string;
  secondaryField?: string;
  fields: ItemFieldConfig[];
  createItem: () => Record<string, unknown>;
};

export const ITEM_DEFINITIONS: ItemDefinition[] = [
  {
    key: "profiles",
    title: "Profiles",
    singularTitle: "Profile",
    description: "Links and handles shown alongside the resume basics.",
    primaryField: "network",
    secondaryField: "username",
    fields: [
      { key: "icon", label: "Icon", type: "text", placeholder: "github" },
      { key: "network", label: "Network", type: "text" },
      { key: "username", label: "Username", type: "text" },
      {
        key: "website.url",
        label: "Website",
        type: "text",
        placeholder: "https://...",
      },
      {
        key: "options.showLinkInTitle",
        label: "Show link in title",
        type: "toggle",
      },
    ],
    createItem: () => ({
      id: crypto.randomUUID(),
      hidden: false,
      icon: "",
      network: "",
      username: "",
      website: { label: "", url: "" },
      options: { showLinkInTitle: false },
    }),
  },
  {
    key: "experience",
    title: "Experience",
    singularTitle: "Experience entry",
    description: "Roles, companies, and rich descriptions.",
    primaryField: "company",
    secondaryField: "position",
    fields: [
      { key: "company", label: "Company", type: "text" },
      { key: "location", label: "Location", type: "text" },
      { key: "position", label: "Position", type: "text" },
      { key: "period", label: "Period", type: "text" },
      {
        key: "website.url",
        label: "Website",
        type: "text",
        placeholder: "https://...",
      },
      {
        key: "options.showLinkInTitle",
        label: "Show link in title",
        type: "toggle",
      },
      { key: "description", label: "Description", type: "richtext" },
    ],
    createItem: () => ({
      id: crypto.randomUUID(),
      hidden: false,
      company: "",
      location: "",
      position: "",
      period: "",
      website: { label: "", url: "" },
      options: { showLinkInTitle: false },
      description: "",
      roles: [],
    }),
  },
  {
    key: "education",
    title: "Education",
    singularTitle: "Education entry",
    description: "Schooling, degrees, and achievements.",
    primaryField: "school",
    secondaryField: "degree",
    fields: [
      { key: "school", label: "School", type: "text" },
      { key: "area", label: "Area", type: "text" },
      { key: "degree", label: "Degree", type: "text" },
      { key: "grade", label: "Grade", type: "text" },
      { key: "location", label: "Location", type: "text" },
      { key: "period", label: "Period", type: "text" },
      { key: "website.url", label: "Website", type: "text" },
      {
        key: "options.showLinkInTitle",
        label: "Show link in title",
        type: "toggle",
      },
      { key: "description", label: "Description", type: "richtext" },
    ],
    createItem: () => ({
      id: crypto.randomUUID(),
      hidden: false,
      school: "",
      area: "",
      degree: "",
      grade: "",
      location: "",
      period: "",
      website: { label: "", url: "" },
      options: { showLinkInTitle: false },
      description: "",
    }),
  },
  {
    key: "projects",
    title: "Projects",
    singularTitle: "Project",
    description: "The projects JobOps will use for tailoring.",
    primaryField: "name",
    secondaryField: "period",
    fields: [
      { key: "name", label: "Name", type: "text" },
      { key: "period", label: "Period", type: "text" },
      { key: "website.url", label: "Website", type: "text" },
      {
        key: "options.showLinkInTitle",
        label: "Show link in title",
        type: "toggle",
      },
      { key: "description", label: "Description", type: "richtext" },
      { key: "technologies", label: "Keywords", type: "tags" },
    ],
    createItem: () => ({
      id: crypto.randomUUID(),
      hidden: false,
      name: "",
      period: "",
      website: { label: "", url: "" },
      options: { showLinkInTitle: false },
      description: "",
      technologies: [],
    }),
  },
  {
    key: "skills",
    title: "Skills",
    singularTitle: "Skill group",
    description: "Categories and keywords used for tailoring output.",
    primaryField: "name",
    secondaryField: "proficiency",
    fields: [
      { key: "icon", label: "Icon", type: "text" },
      { key: "name", label: "Name", type: "text" },
      { key: "proficiency", label: "Proficiency", type: "text" },
      { key: "level", label: "Level", type: "number", min: 0, step: 1 },
      { key: "keywords", label: "Keywords", type: "tags" },
    ],
    createItem: () => ({
      id: crypto.randomUUID(),
      hidden: false,
      icon: "",
      name: "",
      proficiency: "",
      level: 3,
      keywords: [],
    }),
  },
  {
    key: "languages",
    title: "Languages",
    singularTitle: "Language",
    description: "Spoken or written languages.",
    primaryField: "language",
    secondaryField: "fluency",
    fields: [
      { key: "language", label: "Language", type: "text" },
      { key: "fluency", label: "Fluency", type: "text" },
      { key: "level", label: "Level", type: "number", min: 0, step: 1 },
    ],
    createItem: () => ({
      id: crypto.randomUUID(),
      hidden: false,
      language: "",
      fluency: "",
      level: 3,
    }),
  },
  {
    key: "interests",
    title: "Interests",
    singularTitle: "Interest",
    description: "Interests and topic clusters.",
    primaryField: "name",
    secondaryField: "icon",
    fields: [
      { key: "icon", label: "Icon", type: "text" },
      { key: "name", label: "Name", type: "text" },
      { key: "keywords", label: "Keywords", type: "tags" },
    ],
    createItem: () => ({
      id: crypto.randomUUID(),
      hidden: false,
      icon: "",
      name: "",
      keywords: [],
    }),
  },
  {
    key: "awards",
    title: "Awards",
    singularTitle: "Award",
    description: "Awards and recognitions.",
    primaryField: "title",
    secondaryField: "awarder",
    fields: [
      { key: "title", label: "Title", type: "text" },
      { key: "awarder", label: "Awarder", type: "text" },
      { key: "date", label: "Date", type: "text" },
      { key: "website.url", label: "Website", type: "text" },
      {
        key: "options.showLinkInTitle",
        label: "Show link in title",
        type: "toggle",
      },
      { key: "description", label: "Description", type: "richtext" },
    ],
    createItem: () => ({
      id: crypto.randomUUID(),
      hidden: false,
      title: "",
      awarder: "",
      date: "",
      website: { label: "", url: "" },
      options: { showLinkInTitle: false },
      description: "",
    }),
  },
  {
    key: "certifications",
    title: "Certifications",
    singularTitle: "Certification",
    description: "Formal certificates and credentials.",
    primaryField: "title",
    secondaryField: "issuer",
    fields: [
      { key: "title", label: "Title", type: "text" },
      { key: "issuer", label: "Issuer", type: "text" },
      { key: "date", label: "Date", type: "text" },
      { key: "website.url", label: "Website", type: "text" },
      {
        key: "options.showLinkInTitle",
        label: "Show link in title",
        type: "toggle",
      },
      { key: "description", label: "Description", type: "richtext" },
    ],
    createItem: () => ({
      id: crypto.randomUUID(),
      hidden: false,
      title: "",
      issuer: "",
      date: "",
      website: { label: "", url: "" },
      options: { showLinkInTitle: false },
      description: "",
    }),
  },
  {
    key: "publications",
    title: "Publications",
    singularTitle: "Publication",
    description: "Published writing and papers.",
    primaryField: "title",
    secondaryField: "publisher",
    fields: [
      { key: "title", label: "Title", type: "text" },
      { key: "publisher", label: "Publisher", type: "text" },
      { key: "date", label: "Date", type: "text" },
      { key: "website.url", label: "Website", type: "text" },
      {
        key: "options.showLinkInTitle",
        label: "Show link in title",
        type: "toggle",
      },
      { key: "description", label: "Description", type: "richtext" },
    ],
    createItem: () => ({
      id: crypto.randomUUID(),
      hidden: false,
      title: "",
      publisher: "",
      date: "",
      website: { label: "", url: "" },
      options: { showLinkInTitle: false },
      description: "",
    }),
  },
  {
    key: "volunteer",
    title: "Volunteer",
    singularTitle: "Volunteer entry",
    description: "Volunteer work and community contributions.",
    primaryField: "organization",
    secondaryField: "position",
    fields: [
      { key: "organization", label: "Organization", type: "text" },
      { key: "location", label: "Location", type: "text" },
      { key: "period", label: "Period", type: "text" },
      { key: "position", label: "Position", type: "text" },
      { key: "website.url", label: "Website", type: "text" },
      {
        key: "options.showLinkInTitle",
        label: "Show link in title",
        type: "toggle",
      },
      { key: "description", label: "Description", type: "richtext" },
    ],
    createItem: () => ({
      id: crypto.randomUUID(),
      hidden: false,
      organization: "",
      location: "",
      period: "",
      position: "",
      website: { label: "", url: "" },
      options: { showLinkInTitle: false },
      description: "",
    }),
  },
  {
    key: "references",
    title: "References",
    singularTitle: "Reference",
    description: "References and supporting contacts.",
    primaryField: "name",
    secondaryField: "position",
    fields: [
      { key: "name", label: "Name", type: "text" },
      { key: "position", label: "Position", type: "text" },
      { key: "phone", label: "Phone", type: "text" },
      { key: "website.url", label: "Website", type: "text" },
      {
        key: "options.showLinkInTitle",
        label: "Show link in title",
        type: "toggle",
      },
      { key: "description", label: "Description", type: "richtext" },
    ],
    createItem: () => ({
      id: crypto.randomUUID(),
      hidden: false,
      name: "",
      position: "",
      phone: "",
      website: { label: "", url: "" },
      options: { showLinkInTitle: false },
      description: "",
    }),
  },
];
